pull_request_rules:
- name: automatic merge on CI success and review
  conditions:
        - status-success=Jenkins Tests
        - base=master
  actions:
        merge:
            method: merge
            strict: true

