pull_request_rules:
- name: automatic merge on CI success and review
conditions:
        - status-success=continuous-integration/jenkins/pr-head
        - base=master
    actions:
        merge:
            method: merge
            strict: true
