pull_request_rules:
- name: automatic merge on CI success and review
conditions:
- "#approved-reviews-by>=1"
- status-success=continuous-integration/jenkins/pr-head
- status-success=license/cla
actions:
    merge:
        method: merge
        strict: true
